const productcontroller=require("../controllers/Products/getproductcontroller");
const express=require("express");
const router=express.Router();
router.get("/",productcontroller);
router.get("/category/:category",productcontroller);
router.get("/name/:name",productcontroller);
router.get("/subcategory/:subcategory",productcontroller);
router.get("/id/:id",productcontroller);
router.get("/random",productcontroller);
router.get("/top-rated",productcontroller);
router.get("/lowtohigh",productcontroller);
router.get("/hightolow",productcontroller);
module.exports=router;
